version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "09:00"
      timezone: "Asia/Istanbul"
    open-pull-requests-limit: 10
    target-branch: main
    versioning-strategy: increase
    labels:
      - "dependencies"
