name: GitHub Actions Demo
on: [ push ]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Lint
        run: |
          npm run lint:ci
      - name: Tests
        run: |
          npm test
